In [2]:
import numpy as np

def jacobi_rotation_solver(M, tol=1e-10, limit=100):
    dim = M.shape[0]

    if not np.allclose(M, M.T, atol=1e-12):
        raise ValueError("Ожидается симметричная матрица.")

    eig_vecs = np.identity(dim)
    matrix = M.copy()

    for iteration in range(limit):
        # Поиск максимального вне диагонали
        off_diag_max = 0.0
        row, col = 0, 1
        for i in range(dim):
            for j in range(i + 1, dim):
                if abs(matrix[i, j]) > off_diag_max:
                    off_diag_max = abs(matrix[i, j])
                    row, col = i, j

        if off_diag_max < tol:
            break

        delta = matrix[row, row] - matrix[col, col]
        if delta == 0:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan2(2 * matrix[row, col], delta)

        rot = np.identity(dim)
        cos_theta = np.cos(theta)
        sin_theta = np.sin(theta)

        rot[row, row] = cos_theta
        rot[col, col] = cos_theta
        rot[row, col] = -sin_theta
        rot[col, row] = sin_theta

        matrix = rot.T @ matrix @ rot
        eig_vecs = eig_vecs @ rot

    eig_vals = np.diagonal(matrix)
    return eig_vals, eig_vecs

# Пример
B = np.array([
    [5, 1, 2],
    [1, 4, 1],
    [2, 1, 3]
])

print("Входная матрица:\n", B)

vals, vecs = jacobi_rotation_solver(B)

print("\nНайденные собственные значения:")
print(vals)

print("\nСоответствующие собственные векторы:")
print(vecs)

Входная матрица:
 [[5 1 2]
 [1 4 1]
 [2 1 3]]

Найденные собственные значения:
[6.89510652 3.39729507 1.70759841]

Соответствующие собственные векторы:
[[ 0.75257583 -0.45794385 -0.47319874]
 [ 0.43170413  0.88573564 -0.17059871]
 [ 0.49725362 -0.07589338  0.86427949]]
